site_name: PPS - Unidad1 - TareaRA1 - Óscar Polo Fernández
theme:
  name: mkdocs

nav:
  - Inicio: index.md
  - 1. Elementos de Python: elementos_python.md
  - 2. Ejecución y Depuración: ejecucion_depuracion.md
  - 3. Pruebas: pruebas.md
  - 4. Ejecución en Sandbox: sandbox.md
  - 5. Reflexión: reflexion.md
  - 6. Código fuente: codigofuente.md
  - 7. Tests: tests.md

