site_name: PPS - Unidad1 - TareaRA1 - Óscar Polo Fernández
theme:
  name: mkdocs

nav:
  - 1. Índice: index.md
  - 2. Elementos de Python: elementos_python.md
  - 3. Ejecución y Depuración: ejecucion_depuracion.md
  - 4. Pruebas: pruebas.md
  - 5. Ejecución en Sandbox: sandbox.md
  - 6. Reflexión: reflexion.md
  - 7. Código fuente: codigofuente.md
  - 8. Tests: tests.md

